### ISSUE TITLE
Followed, but unsuccessfully...

### ISSUE THREAD

**Issue by ghost** [jollyjinx/AppleMobileConfigForEAPWiFi#2]
First, thanks for the description - it is really helpful to understand what's going on in the depth of Apple's products.

Unfortunately, I did not succeed in creating a profile for a WPA3 Enterprise setup. I tried it with my iPhone 12 pro first, before going to the HomePods, but it didn't work there as well.

I have a Synology MR2200AC router, and that router has two places where certificates come into the game:

- First, under System Control: There is an option to download the router's certificate, with its private key, as archive.
- Second, under Radius Server: There the Root certificate can be downloaded.

Would you mind to point out which of these certificates shall be used in each of the three openssl steps you're describing? This would help me to get closer to the problem root.
 
Thanks a lot!

**Comment by jollyjinx** [comment]
Hello  Gerhard,

you don’t need private keys - you only need the public key of the EAP certificate of your WiFi network (if your WiFI certificate is self signed) so that the HomePod accepts it. I think it’s the radius certificate that you need as it’s probably shown when you first enter that network. You should be asked to accept that certificate when you enter the network the first time with your iPhone as well.

Hope that helps - Patrick
